# Generated by Django 5.1.7 on 2025-04-20 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userreport',
            name='report_type',
        ),
    ]
