# Generated by Django 5.1.7 on 2025-04-20 17:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_userreport_report_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreport',
            name='time_stamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
