# Generated by Django 5.1.7 on 2025-05-03 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_frequentquestions_userreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='InitalQuizQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=500, null=True)),
                ('answers', models.JSONField(blank=True, null=True)),
                ('correct_answer', models.CharField(blank=True, max_length=1, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='inital_quiz',
            field=models.BooleanField(default=False),
        ),
    ]
