# Generated by Django 5.1.7 on 2025-05-03 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_initalquizquestions_userprofile_inital_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreport',
            name='difficulty',
            field=models.CharField(choices=[('initial', 'Initial'), ('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=20),
        ),
    ]
